### Get all users
GET http://localhost:3000/api/users
Content-Type: application/json

### Get a user by ID
GET http://localhost:3000/api/users/15
Content-Type: application/json

### Create a new user
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "username": "vvv",
  "email": "vvvvvsdgfasdgvvvv@example.com",
  "password": "12345",
  "filename": "profile.jpg",
  "address": "Testitie 12",
  "role": "user"
}

### Update a user by ID
PUT http://localhost:3000/api/users/24
Content-Type: application/json

{
  "username": "updateduser",
  "email": "updateduser@example.com",
  "password": "newpassword123",
  "filename": "updated-profile.jpg",
  "address": "Updated Address",
  "role": "admin"
}

### Delete a user by ID
DELETE http://localhost:3000/api/users/20
Content-Type: application/json