### GET orders (Needs admin or employee role)
GET http://localhost:3000/api/orders
Content-Type: application/json


### GET user's orders  (needs token)
GET http://localhost:3000/api/orders/myorders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyMzAsInVzZXJuYW1lIjoidGVzdGlwZW5hIiwiZmlyc3RfbmFtZSI6IlBlbnR0aSIsImxhc3RfbmFtZSI6IkhpZWtrYXZ1b3JpIiwiZW1haWwiOiJ0ZXN0aXhkQG1ldHJvcG9saWEuZmlhc2QiLCJhZGRyZXNzIjoibWFsbWluIGFzc2EiLCJwaG9uZSI6NTA0MzgxMDQ5LCJyb2xlIjoidXNlciIsImZpbGVuYW1lIjoidXBsb2Fkcy8xZjJjOGY4MDU5MzhjMmI4YmVlYmI5OGM2Njc4NWRkY190aHVtYi5qcGciLCJjcmVhdGVkX2F0IjoiMjAyNS0wNS0wMlQyMToxNDoyMC4wMDBaIiwiaWF0IjoxNzQ2MzgzOTc0LCJleHAiOjE3NDYzODc1NzR9.J0edTZj8Slos1OOCQ__B7tFboIg53BjkJog_h_EfCwk

### POST order
POST http://localhost:3000/api/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyMzAsInVzZXJuYW1lIjoidGVzdGlwZW5hIiwiZmlyc3RfbmFtZSI6IlBlbnR0aSIsImxhc3RfbmFtZSI6IkhpZWtrYXZ1b3JpIiwiZW1haWwiOiJ0ZXN0aXhkQG1ldHJvcG9saWEuZmlhc2QiLCJhZGRyZXNzIjoibWFsbWluIGFzc2EiLCJwaG9uZSI6NTA0MzgxMDQ5LCJyb2xlIjoidXNlciIsImZpbGVuYW1lIjoidXBsb2Fkcy8xZjJjOGY4MDU5MzhjMmI4YmVlYmI5OGM2Njc4NWRkY190aHVtYi5qcGciLCJjcmVhdGVkX2F0IjoiMjAyNS0wNS0wMlQyMToxNDoyMC4wMDBaIiwiaWF0IjoxNzQ2MzgzOTc0LCJleHAiOjE3NDYzODc1NzR9.J0edTZj8Slos1OOCQ__B7tFboIg53BjkJog_h_EfCwk

{
  "listOfProducts": [4,4,4,6,7,8,8,8],
  "total_price": 999
}


###Put order (To modify the status of the order)
PUT http://localhost:3000/api/orders
Content-Type: application/json
Authorization: Bearer "TOKEN"

{
 "status": "preparing"
}